org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=36
version.name=1.11.4
version.code=1035

module.id=eu.hxreborn.biometricapplock
module.name=Biometric App Locker
module.author=hxreborn
module.description=Enforces biometric auth on any app at the System Framework level.
xposed.api.min=101
xposed.api.target=102

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
